import os
import sys
import googleapiclient.discovery
from googleapiclient.http import MediaFileUpload
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request

# PERMISSIONS
SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

def authenticate():
    print("--- Authenticating (Server Mode) ---")
    if not os.path.exists("token.json"):
        sys.exit("❌ Error: token.json missing.")

    creds = Credentials.from_authorized_user_file("token.json", SCOPES)
    
    if not creds.valid:
        if creds.expired and creds.refresh_token:
            print("   ⏳ Refreshing token...")
            creds.refresh(Request())
        else:
            sys.exit("❌ Auth Error: Invalid token.")

    return googleapiclient.discovery.build("youtube", "v3", credentials=creds)

def upload_video(file_path):
    youtube = authenticate()
    print(f"--- Uploading Publicly: {file_path} ---")
    
    body = {
        "snippet": {
            "title": "Daily AI Fact 🤖 #shorts",
            "description": "Generated by Python. #ai #automation #coding",
            "tags": ["shorts", "ai", "python"],
            "categoryId": "28" # Science & Tech
        },
        "status": {
            # --- THE BIG CHANGE ---
            "privacyStatus": "public", 
            "selfDeclaredMadeForKids": False
        }
    }
    
    media = MediaFileUpload(file_path, chunksize=-1, resumable=True)
    request = youtube.videos().insert(part="snippet,status", body=body, media_body=media)
    
    response = None
    while response is None:
        status, response = request.next_chunk()
        if status:
            print(f"   Uploading... {int(status.progress() * 100)}%")
            
    print(f"✅ UPLOAD SUCCESS! https://youtube.com/shorts/{response.get('id')}")

if __name__ == "__main__":
    if os.path.exists("final_short_automated.mp4"):
        upload_video("final_short_automated.mp4")
    else:
        print("❌ Video file not found.")
